### ISSUE TITLE
Please add a license 

### ISSUE THREAD

**Issue by davlum** [cloudiator/livy-server-docker#5]
I just mindlessly forked this without checking for a license first. Looks like a few other forks exist as well. I'm realizing now that [according to this](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license/5874#5874) I should not be assuming much about the how the code should be treated without a license.

**Comment by seybi87** [comment]
Hi @davlum , thanks for pointing this out. I have added the Apache-2.0 license.
